def print_flowchart():
    print("Start")
    print("  ↓")
    print("Ask user to enter an animal")
    print("  ↓")
    print("Is animal 'cat'?")
    print("  → Yes: print 'Meow'")
    print("  → No: check next animal")
    print("Is animal 'dog'?")
    print("  → Yes: print 'Woof'")
    print("  → No: check next animal")
    print("Is animal 'cow'?")
    print("  → Yes: print 'Moo'")
    print("  → No: check next animal")
    print("Is animal 'duck'?")
    print("  → Yes: print 'Quack'")
    print("  → No: print 'I don't know that animal'")
    print("End")

print_flowchart()
